import type { Order } from "./types"

export const mockOrders: Order[] = [
  // ── Warehouse Processing (5) ─────────────────────────────────────
  {
    id: "SO1086013",
    channelOrderNo: "113-3056495-6289014",
    referenceNo: "35690538-30-513430",
    channel: "amazon",
    channelName: "Amazon US",
    status: "warehouse_processing",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Shannon Smith", country: "US" },
    lineItems: [
      {
        id: "li-001",
        channelSku: "AMZ-UBP-40010",
        channelProductName: "UBP 40010 6PK Bundle",
        qty: 1,
        unitPrice: 44.40,
        omsSku: "UBP-40010-6PK",
        omsProductName: "Ultra Bright Pro 40010 6-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001234",
        availQty: 84,
        backorderQty: 0,
        location: "A-12-3",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 44.40,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-04-21T12:33:00Z",
    shipDate: null,
    ingestedAt: "2026-04-21T12:35:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO1085963",
    channelOrderNo: "113-5298114-1943404",
    referenceNo: "35690495-30-513428",
    channel: "amazon",
    channelName: "Amazon US",
    status: "warehouse_processing",
    dropShipStatus: "none",
    isExpedited: true,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Aiden Zheng", country: "US" },
    lineItems: [
      {
        id: "li-002",
        channelSku: "AMZ-RB-19573",
        channelProductName: "RB 19573 3PK",
        qty: 2,
        unitPrice: 26.00,
        omsSku: "RB-19573-3PK",
        omsProductName: "RunBoost 19573 3-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001235",
        availQty: 52,
        backorderQty: 0,
        location: "B-04-1",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 52.00,
    totalQty: 2,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-03-28T02:26:00Z",
    shipDate: null,
    ingestedAt: "2026-03-28T02:28:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO1085132",
    channelOrderNo: "114-3807709-3293836",
    referenceNo: "35689774-30-513403",
    channel: "amazon",
    channelName: "Amazon US",
    status: "warehouse_processing",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Sandra Sancewich", country: "US" },
    lineItems: [
      {
        id: "li-003",
        channelSku: "AMZ-NATR-2006",
        channelProductName: "NATR 2006 3PK",
        qty: 1,
        unitPrice: 31.57,
        omsSku: "NATR-2006-3PK",
        omsProductName: "Nature Series 2006 3-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002301",
        availQty: 33,
        backorderQty: 0,
        location: "C-07-2",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 31.57,
    totalQty: 1,
    warehouseName: "LA-WH-02",
    orderDate: "2026-03-26T05:59:00Z",
    shipDate: null,
    ingestedAt: "2026-03-26T06:01:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO1084882",
    channelOrderNo: "5773571890990605556",
    referenceNo: "SO19037111",
    channel: "tiktok",
    channelName: "TikTok Shop",
    status: "warehouse_processing",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Mary Leikam", country: "US" },
    lineItems: [
      {
        id: "li-004",
        channelSku: "TT-PB-50008",
        channelProductName: "PowerBoost 50008",
        qty: 1,
        unitPrice: 15.14,
        omsSku: "PB-50008",
        omsProductName: "PowerBoost Pro 50008",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001890",
        availQty: 210,
        backorderQty: 0,
        location: "D-02-4",
        defaultVendor: "PIQ Vendor",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 15.14,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-02-11T20:33:00Z",
    shipDate: null,
    ingestedAt: "2026-02-11T20:35:00Z",
    company: "PIQ",
    hasExceptions: false,
  },
  {
    id: "SO1084489",
    channelOrderNo: "5773571716763407",
    referenceNo: "SO19037110",
    channel: "tiktok",
    channelName: "TikTok Shop",
    status: "warehouse_processing",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Lechiqu1004 Mustelier", country: "US" },
    lineItems: [
      {
        id: "li-005",
        channelSku: "TT-PB-50008",
        channelProductName: "PowerBoost 50008",
        qty: 1,
        unitPrice: 15.67,
        omsSku: "PB-50008",
        omsProductName: "PowerBoost Pro 50008",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001890",
        availQty: 209,
        backorderQty: 0,
        location: "D-02-4",
        defaultVendor: "PIQ Vendor",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 15.67,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-01-24T08:54:00Z",
    shipDate: null,
    ingestedAt: "2026-01-24T08:56:00Z",
    company: "PIQ",
    hasExceptions: false,
  },

  // ── Processing (4) ───────────────────────────────────────────────
  {
    id: "SO1083210",
    channelOrderNo: "SHO-2891023-US",
    referenceNo: "REF-83210",
    channel: "shopify",
    channelName: "Shopify US Store",
    status: "processing",
    dropShipStatus: "pending",
    isExpedited: true,
    isPaid: true,
    hasShipment: false,
    isDomestic: false,
    holdReason: null,
    customer: { name: "Eduardo Chong", country: "CA" },
    lineItems: [
      {
        id: "li-006",
        channelSku: "SHP-NAT-2004",
        channelProductName: "NAT-2004 Bundle",
        qty: 2,
        unitPrice: 6.50,
        omsSku: "NAT-2004",
        omsProductName: "Natural Series 2004",
        omsMatched: true,
        warehouseId: "wh-03",
        warehouseName: "NY-WH-03",
        warehouseSku: "WH-003100",
        availQty: 18,
        backorderQty: 0,
        location: "E-01-1",
        defaultVendor: "N/A",
        warehouseMapped: true,
        issues: [],
      },
      {
        id: "li-007",
        channelSku: "SHP-IB-60002",
        channelProductName: "IB-60002 2PK",
        qty: 1,
        unitPrice: 10.43,
        omsSku: "IB-60002-2PK",
        omsProductName: "IceBurst 60002 2-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001950",
        availQty: 7,
        backorderQty: 0,
        location: "F-06-3",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 23.43,
    totalQty: 3,
    warehouseName: "NY-WH-03",
    orderDate: "2026-01-15T07:41:00Z",
    shipDate: null,
    ingestedAt: "2026-01-15T07:43:00Z",
    company: "N",
    hasExceptions: false,
  },
  {
    id: "SO1082950",
    channelOrderNo: "WMT-9928374-1",
    referenceNo: "REF-82950",
    channel: "walmart",
    channelName: "Walmart Marketplace",
    status: "processing",
    dropShipStatus: "sent",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "James Vincent", country: "US" },
    lineItems: [
      {
        id: "li-008",
        channelSku: "WMT-IB-60002",
        channelProductName: "IceBurst 60002 2PK",
        qty: 1,
        unitPrice: 21.34,
        omsSku: "IB-60002-2PK",
        omsProductName: "IceBurst 60002 2-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001950",
        availQty: 45,
        backorderQty: 0,
        location: "F-06-3",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 21.34,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-01-13T08:00:00Z",
    shipDate: null,
    ingestedAt: "2026-01-13T08:02:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO1082741",
    channelOrderNo: "114-2298884-4724238",
    referenceNo: "REF-82741",
    channel: "amazon",
    channelName: "Amazon US",
    status: "processing",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: false,
    holdReason: null,
    customer: { name: "Ana Cecilia Larrazabal", country: "MX" },
    lineItems: [
      {
        id: "li-009",
        channelSku: "AMZ-RB-19613",
        channelProductName: "RB 19613 3PACK",
        qty: 1,
        unitPrice: 53.49,
        omsSku: "RB-19613-3PACK",
        omsProductName: "RunBoost 19613 3-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002450",
        availQty: 22,
        backorderQty: 0,
        location: "G-09-1",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 53.49,
    totalQty: 1,
    warehouseName: "LA-WH-02",
    orderDate: "2026-01-15T07:41:00Z",
    shipDate: null,
    ingestedAt: "2026-01-15T07:43:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO1082590",
    channelOrderNo: "114-7523452-8165006",
    referenceNo: "REF-82590",
    channel: "amazon",
    channelName: "Amazon US",
    status: "processing",
    dropShipStatus: "confirmed",
    isExpedited: true,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Joyce West", country: "US" },
    lineItems: [
      {
        id: "li-010",
        channelSku: "AMZ-UB-40041",
        channelProductName: "UB-40041",
        qty: 1,
        unitPrice: 30.49,
        omsSku: "UB-40041",
        omsProductName: "UltraBright 40041",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001770",
        availQty: 66,
        backorderQty: 0,
        location: "H-11-2",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 30.49,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-01-12T06:20:00Z",
    shipDate: null,
    ingestedAt: "2026-01-12T06:22:00Z",
    company: "OTB",
    hasExceptions: false,
  },

  // ── On Hold (5) ──────────────────────────────────────────────────
  {
    id: "SO6047719",
    channelOrderNo: "111-2255325-2352264",
    referenceNo: "REF-6047719",
    channel: "amazon",
    channelName: "Amazon US",
    status: "on_hold",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: false,
    hasShipment: false,
    isDomestic: true,
    holdReason: "Payment review",
    customer: { name: "Shannon Smith", country: "US" },
    lineItems: [
      {
        id: "li-011",
        channelSku: "AMZ-UBP-40010-6PK",
        channelProductName: "UBP-40010-6PK",
        qty: 1,
        unitPrice: 44.40,
        omsSku: "UBP-40010-6PK",
        omsProductName: "Ultra Bright Pro 40010 6-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001234",
        availQty: 84,
        backorderQty: 0,
        location: "A-12-3",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 44.40,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-03-29T12:33:00Z",
    shipDate: null,
    ingestedAt: "2026-03-29T12:35:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO6045999",
    channelOrderNo: "112-5298114-1943404",
    referenceNo: "REF-6045999",
    channel: "amazon",
    channelName: "Amazon US",
    status: "on_hold",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: false,
    hasShipment: false,
    isDomestic: true,
    holdReason: "Address verification failed",
    customer: { name: "Aiden Zheng", country: "US" },
    lineItems: [
      {
        id: "li-012",
        channelSku: "AMZ-RB-19573-3PK",
        channelProductName: "RB-19573-3PK",
        qty: 1,
        unitPrice: 52.00,
        omsSku: "RB-19573-3PK",
        omsProductName: "RunBoost 19573 3-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001235",
        availQty: 52,
        backorderQty: 0,
        location: "B-04-1",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 52.00,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-03-28T02:26:00Z",
    shipDate: null,
    ingestedAt: "2026-03-28T02:28:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO6039316",
    channelOrderNo: "114-3807709-3293836",
    referenceNo: "REF-6039316",
    channel: "amazon",
    channelName: "Amazon US",
    status: "on_hold",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: "Fraud check",
    customer: { name: "Sandra Sancewich", country: "US" },
    lineItems: [
      {
        id: "li-013",
        channelSku: "AMZ-NATR-2006",
        channelProductName: "NATR-2006-3PK",
        qty: 1,
        unitPrice: 31.57,
        omsSku: "NATR-2006-3PK",
        omsProductName: "Nature Series 2006 3-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002301",
        availQty: 33,
        backorderQty: 0,
        location: "C-07-2",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 31.57,
    totalQty: 1,
    warehouseName: "LA-WH-02",
    orderDate: "2026-03-26T05:59:00Z",
    shipDate: null,
    ingestedAt: "2026-03-26T06:01:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO5870592",
    channelOrderNo: "113-6689917-1202666",
    referenceNo: "REF-5870592",
    channel: "amazon",
    channelName: "Amazon US",
    status: "on_hold",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: false,
    hasShipment: false,
    isDomestic: true,
    holdReason: "Customer request",
    customer: { name: "Al Cameron", country: "US" },
    lineItems: [
      {
        id: "li-014",
        channelSku: "AMZ-RB-19605-3PK",
        channelProductName: "RB-19605-3PK",
        qty: 1,
        unitPrice: 115.24,
        omsSku: "RB-19605-3PK",
        omsProductName: "RunBoost 19605 3-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001560",
        availQty: 11,
        backorderQty: 0,
        location: "A-05-2",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 115.24,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-01-24T08:54:00Z",
    shipDate: null,
    ingestedAt: "2026-01-24T08:56:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO5853078",
    channelOrderNo: "113-1138017-5033817",
    referenceNo: "REF-5853078",
    channel: "amazon",
    channelName: "Amazon US",
    status: "on_hold",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: false,
    holdReason: "Awaiting customs documentation",
    customer: { name: "Emily Linares", country: "MX" },
    lineItems: [
      {
        id: "li-015",
        channelSku: "AMZ-PB-50020-3PK",
        channelProductName: "PB-50020-3PK",
        qty: 1,
        unitPrice: 32.34,
        omsSku: "PB-50020-3PK",
        omsProductName: "PowerBoost 50020 3-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002610",
        availQty: 28,
        backorderQty: 0,
        location: "B-10-1",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 32.34,
    totalQty: 1,
    warehouseName: "LA-WH-02",
    orderDate: "2026-01-17T11:56:00Z",
    shipDate: null,
    ingestedAt: "2026-01-17T11:58:00Z",
    company: "OTB",
    hasExceptions: false,
  },

  // ── Exception (5) ────────────────────────────────────────────────
  {
    id: "SO5913864",
    channelOrderNo: "129104347254846",
    referenceNo: "REF-5913864",
    channel: "walmart",
    channelName: "Walmart Marketplace",
    status: "exception",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Mary Leikam", country: "US" },
    lineItems: [
      {
        id: "li-016",
        channelSku: "84715",
        channelProductName: "84715",
        qty: 1,
        unitPrice: 15.14,
        omsSku: null,
        omsProductName: null,
        omsMatched: false,
        warehouseId: null,
        warehouseName: null,
        warehouseSku: null,
        availQty: 0,
        backorderQty: 0,
        location: null,
        defaultVendor: null,
        warehouseMapped: false,
        issues: ["sku_not_exist"],
      },
    ],
    grandTotal: 15.14,
    totalQty: 1,
    warehouseName: null,
    orderDate: "2026-02-11T20:33:00Z",
    shipDate: null,
    ingestedAt: "2026-02-11T20:35:00Z",
    company: "PIQ",
    hasExceptions: true,
  },
  {
    id: "SO5841164",
    channelOrderNo: "112-7523452-8165006",
    referenceNo: "REF-5841164",
    channel: "amazon",
    channelName: "Amazon US",
    status: "exception",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "James Vincent", country: "US" },
    lineItems: [
      {
        id: "li-017",
        channelSku: "AMZ-IB-60002-2PK",
        channelProductName: "IB-60002-2PK",
        qty: 1,
        unitPrice: 21.34,
        omsSku: "IB-60002-2PK",
        omsProductName: "IceBurst 60002 2-Pack",
        omsMatched: true,
        warehouseId: null,
        warehouseName: null,
        warehouseSku: null,
        availQty: 0,
        backorderQty: 0,
        location: null,
        defaultVendor: null,
        warehouseMapped: false,
        issues: ["no_warehouse"],
      },
    ],
    grandTotal: 21.34,
    totalQty: 1,
    warehouseName: null,
    orderDate: "2026-01-13T08:00:00Z",
    shipDate: null,
    ingestedAt: "2026-01-13T08:02:00Z",
    company: "OTB",
    hasExceptions: true,
  },
  {
    id: "SO5838591",
    channelOrderNo: "112-5528871-8304248",
    referenceNo: "REF-5838591",
    channel: "amazon",
    channelName: "Amazon US",
    status: "exception",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: false,
    holdReason: null,
    customer: { name: "Joyce West", country: "CA" },
    lineItems: [
      {
        id: "li-018",
        channelSku: "AMZ-UB-40041-INTL",
        channelProductName: "UB-40041 International",
        qty: 1,
        unitPrice: 30.49,
        omsSku: null,
        omsProductName: null,
        omsMatched: false,
        warehouseId: null,
        warehouseName: null,
        warehouseSku: null,
        availQty: 0,
        backorderQty: 0,
        location: null,
        defaultVendor: null,
        warehouseMapped: false,
        issues: ["oms_not_matched"],
      },
    ],
    grandTotal: 30.49,
    totalQty: 1,
    warehouseName: null,
    orderDate: "2026-01-12T06:20:00Z",
    shipDate: null,
    ingestedAt: "2026-01-12T06:22:00Z",
    company: "OTB",
    hasExceptions: true,
  },
  {
    id: "SO5820300",
    channelOrderNo: "SHO-4421897-US",
    referenceNo: "REF-5820300",
    channel: "shopify",
    channelName: "Shopify US Store",
    status: "exception",
    dropShipStatus: "none",
    isExpedited: true,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Vivian Diehl", country: "US" },
    lineItems: [
      {
        id: "li-019",
        channelSku: "SHP-RB-19579-2PK",
        channelProductName: "RB-19579-2PK",
        qty: 2,
        unitPrice: 27.98,
        omsSku: "RB-19579-2PK",
        omsProductName: "RunBoost 19579 2-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001680",
        availQty: 0,
        backorderQty: 2,
        location: "A-14-1",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: ["out_of_stock"],
      },
    ],
    grandTotal: 27.98,
    totalQty: 2,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-01-17T02:18:00Z",
    shipDate: null,
    ingestedAt: "2026-01-17T02:20:00Z",
    company: "OTB",
    hasExceptions: true,
  },
  {
    id: "SO5800120",
    channelOrderNo: "SHO-3317624-US",
    referenceNo: "REF-5800120",
    channel: "shopify",
    channelName: "Shopify US Store",
    status: "exception",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Richard Arroll", country: "US" },
    lineItems: [
      {
        id: "li-020",
        channelSku: "SHP-UB-40029-3PK",
        channelProductName: "UB-40029-3PK",
        qty: 2,
        unitPrice: 24.68,
        omsSku: "UB-40029-3PK",
        omsProductName: "UltraBright 40029 3-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001320",
        availQty: 2,
        backorderQty: 0,
        location: "B-03-2",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
      {
        id: "li-020b",
        channelSku: "SHP-RB-19579-2PK",
        channelProductName: "RB-19579-2PK",
        qty: 1,
        unitPrice: 12.34,
        omsSku: "RB-19579-2PK",
        omsProductName: "RunBoost 19579 2-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002116",
        availQty: 1,
        backorderQty: 0,
        location: "G-02-1",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
      {
        id: "li-020c",
        channelSku: "SHP-IB-60019-2PK",
        channelProductName: "IB-60019-2PK",
        qty: 1,
        unitPrice: 0,
        omsSku: "IB-60019-2PK",
        omsProductName: "IceBurst 60019 2-Pack",
        omsMatched: true,
        warehouseId: null,
        warehouseName: null,
        warehouseSku: null,
        availQty: 0,
        backorderQty: 0,
        location: null,
        defaultVendor: null,
        warehouseMapped: false,
        issues: ["no_warehouse"],
      },
    ],
    grandTotal: 37.02,
    totalQty: 4,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-04-21T09:18:00Z",
    shipDate: null,
    ingestedAt: "2026-04-21T09:20:00Z",
    company: "OTB",
    hasExceptions: true,
  },

  // ── Backorder (2) ────────────────────────────────────────────────
  {
    id: "SO5790040",
    channelOrderNo: "SHO-2201003-US",
    referenceNo: "REF-5790040",
    channel: "shopify",
    channelName: "Shopify US Store",
    status: "backorder",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Orlin A Delcid Quintero", country: "US" },
    lineItems: [
      {
        id: "li-021",
        channelSku: "SHP-IB-60019-2PK",
        channelProductName: "IB-60019-2PK",
        qty: 2,
        unitPrice: 26.33,
        omsSku: "IB-60019-2PK",
        omsProductName: "IceBurst 60019 2-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002870",
        availQty: 0,
        backorderQty: 4,
        location: "C-12-3",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: ["backorder"],
      },
    ],
    grandTotal: 26.33,
    totalQty: 2,
    warehouseName: "LA-WH-02",
    orderDate: "2026-04-21T09:13:00Z",
    shipDate: null,
    ingestedAt: "2026-04-21T09:15:00Z",
    company: "OTB",
    hasExceptions: true,
  },
  {
    id: "SO5775200",
    channelOrderNo: "WMT-4410922-3",
    referenceNo: "REF-5775200",
    channel: "walmart",
    channelName: "Walmart Marketplace",
    status: "backorder",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: false,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Barbara Alvarez", country: "US" },
    lineItems: [
      {
        id: "li-022",
        channelSku: "WMT-PB-50008",
        channelProductName: "PB-50008",
        qty: 1,
        unitPrice: 17.69,
        omsSku: "PB-50008",
        omsProductName: "PowerBoost Pro 50008",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001890",
        availQty: 0,
        backorderQty: 5,
        location: "D-02-4",
        defaultVendor: "PIQ Vendor",
        warehouseMapped: true,
        issues: ["backorder"],
      },
    ],
    grandTotal: 17.69,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-04-20T08:41:00Z",
    shipDate: null,
    ingestedAt: "2026-04-20T08:43:00Z",
    company: "PIQ",
    hasExceptions: true,
  },

  // ── Shipped (4) ──────────────────────────────────────────────────
  {
    id: "SO5760010",
    channelOrderNo: "SHO-1109823-US",
    referenceNo: "REF-5760010",
    channel: "shopify",
    channelName: "Shopify US Store",
    status: "shipped",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: true,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Jessica Garcia", country: "US" },
    lineItems: [
      {
        id: "li-023",
        channelSku: "SHP-PB-50008",
        channelProductName: "PB-50008",
        qty: 1,
        unitPrice: 16.76,
        omsSku: "PB-50008",
        omsProductName: "PowerBoost Pro 50008",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001890",
        availQty: 208,
        backorderQty: 0,
        location: "D-02-4",
        defaultVendor: "PIQ Vendor",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 16.76,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-04-19T08:32:00Z",
    shipDate: "2026-04-20T10:00:00Z",
    ingestedAt: "2026-04-19T08:34:00Z",
    company: "PIQ",
    hasExceptions: false,
  },
  {
    id: "SO5748200",
    channelOrderNo: "115-4421789-3301224",
    referenceNo: "REF-5748200",
    channel: "amazon",
    channelName: "Amazon US",
    status: "shipped",
    dropShipStatus: "none",
    isExpedited: true,
    isPaid: true,
    hasShipment: true,
    isDomestic: false,
    holdReason: null,
    customer: { name: "Mariaavila11 Avila", country: "CA" },
    lineItems: [
      {
        id: "li-024",
        channelSku: "AMZ-NAT-2004",
        channelProductName: "NAT-2004",
        qty: 1,
        unitPrice: 13.60,
        omsSku: "NAT-2004",
        omsProductName: "Natural Series 2004",
        omsMatched: true,
        warehouseId: "wh-03",
        warehouseName: "NY-WH-03",
        warehouseSku: "WH-003100",
        availQty: 17,
        backorderQty: 0,
        location: "E-01-1",
        defaultVendor: "N/A",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 13.60,
    totalQty: 1,
    warehouseName: "NY-WH-03",
    orderDate: "2026-04-18T08:38:00Z",
    shipDate: "2026-04-19T09:00:00Z",
    ingestedAt: "2026-04-18T08:40:00Z",
    company: "N",
    hasExceptions: false,
  },
  {
    id: "SO5730090",
    channelOrderNo: "SHO-9982341-US",
    referenceNo: "REF-5730090",
    channel: "shopify",
    channelName: "Shopify US Store",
    status: "shipped",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: true,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Chris Worch", country: "US" },
    lineItems: [
      {
        id: "li-025",
        channelSku: "SHP-NAT-2004",
        channelProductName: "NAT-2004",
        qty: 1,
        unitPrice: 12.62,
        omsSku: "NAT-2004",
        omsProductName: "Natural Series 2004",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001100",
        availQty: 55,
        backorderQty: 0,
        location: "I-06-1",
        defaultVendor: "N/A",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 12.62,
    totalQty: 1,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-04-17T06:18:00Z",
    shipDate: "2026-04-18T08:00:00Z",
    ingestedAt: "2026-04-17T06:20:00Z",
    company: "N",
    hasExceptions: false,
  },
  {
    id: "SO5710050",
    channelOrderNo: "TT-8812934-US",
    referenceNo: "REF-5710050",
    channel: "tiktok",
    channelName: "TikTok Shop",
    status: "partially_shipped",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: true,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Lena Park", country: "US" },
    lineItems: [
      {
        id: "li-026",
        channelSku: "TT-PB-50008",
        channelProductName: "PowerBoost 50008",
        qty: 1,
        unitPrice: 15.00,
        omsSku: "PB-50008",
        omsProductName: "PowerBoost Pro 50008",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001890",
        availQty: 207,
        backorderQty: 0,
        location: "D-02-4",
        defaultVendor: "PIQ Vendor",
        warehouseMapped: true,
        issues: [],
      },
      {
        id: "li-027",
        channelSku: "TT-UB-40041",
        channelProductName: "UB-40041",
        qty: 1,
        unitPrice: 30.00,
        omsSku: "UB-40041",
        omsProductName: "UltraBright 40041",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001770",
        availQty: 0,
        backorderQty: 1,
        location: "H-11-2",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: ["out_of_stock"],
      },
    ],
    grandTotal: 45.00,
    totalQty: 2,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-04-16T10:00:00Z",
    shipDate: "2026-04-17T09:00:00Z",
    ingestedAt: "2026-04-16T10:02:00Z",
    company: "OTB",
    hasExceptions: true,
  },

  // ── Partially Shipped (1 more) ────────────────────────────────────
  {
    id: "SO5695000",
    channelOrderNo: "SHO-7741293-US",
    referenceNo: "REF-5695000",
    channel: "shopify",
    channelName: "Shopify US Store",
    status: "partially_shipped",
    dropShipStatus: "none",
    isExpedited: true,
    isPaid: true,
    hasShipment: true,
    isDomestic: false,
    holdReason: null,
    customer: { name: "Fatima Reyes", country: "MX" },
    lineItems: [
      {
        id: "li-028a",
        channelSku: "SHP-RB-19613-3PACK",
        channelProductName: "RB-19613-3PACK",
        qty: 1,
        unitPrice: 53.49,
        omsSku: "RB-19613-3PACK",
        omsProductName: "RunBoost 19613 3-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002450",
        availQty: 21,
        backorderQty: 0,
        location: "G-09-1",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
      {
        id: "li-028b",
        channelSku: "SHP-NATR-2006-3PK",
        channelProductName: "NATR-2006-3PK",
        qty: 2,
        unitPrice: 31.57,
        omsSku: "NATR-2006-3PK",
        omsProductName: "Nature Series 2006 3-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002301",
        availQty: 0,
        backorderQty: 3,
        location: "C-07-2",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: ["out_of_stock"],
      },
    ],
    grandTotal: 116.63,
    totalQty: 3,
    warehouseName: "LA-WH-02",
    orderDate: "2026-04-15T14:30:00Z",
    shipDate: "2026-04-16T10:00:00Z",
    ingestedAt: "2026-04-15T14:32:00Z",
    company: "OTB",
    hasExceptions: true,
  },

  // ── Delivered (2) ────────────────────────────────────────────────
  {
    id: "SO5680100",
    channelOrderNo: "115-3312890-7823401",
    referenceNo: "REF-5680100",
    channel: "amazon",
    channelName: "Amazon US",
    status: "delivered",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: true,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Tom Bradley", country: "US" },
    lineItems: [
      {
        id: "li-029",
        channelSku: "AMZ-UBP-40010-6PK",
        channelProductName: "UBP-40010-6PK",
        qty: 2,
        unitPrice: 44.40,
        omsSku: "UBP-40010-6PK",
        omsProductName: "Ultra Bright Pro 40010 6-Pack",
        omsMatched: true,
        warehouseId: "wh-01",
        warehouseName: "SZ-WH-01",
        warehouseSku: "WH-001234",
        availQty: 82,
        backorderQty: 0,
        location: "A-12-3",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 88.80,
    totalQty: 2,
    warehouseName: "SZ-WH-01",
    orderDate: "2026-04-10T10:00:00Z",
    shipDate: "2026-04-11T08:00:00Z",
    ingestedAt: "2026-04-10T10:02:00Z",
    company: "OTB",
    hasExceptions: false,
  },
  {
    id: "SO5665000",
    channelOrderNo: "WMT-3301928-5",
    referenceNo: "REF-5665000",
    channel: "walmart",
    channelName: "Walmart Marketplace",
    status: "delivered",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: true,
    hasShipment: true,
    isDomestic: true,
    holdReason: null,
    customer: { name: "Nina Sato", country: "US" },
    lineItems: [
      {
        id: "li-030",
        channelSku: "WMT-NAT-2004",
        channelProductName: "NAT-2004",
        qty: 3,
        unitPrice: 13.60,
        omsSku: "NAT-2004",
        omsProductName: "Natural Series 2004",
        omsMatched: true,
        warehouseId: "wh-03",
        warehouseName: "NY-WH-03",
        warehouseSku: "WH-003100",
        availQty: 14,
        backorderQty: 0,
        location: "E-01-1",
        defaultVendor: "N/A",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 40.80,
    totalQty: 3,
    warehouseName: "NY-WH-03",
    orderDate: "2026-04-08T09:00:00Z",
    shipDate: "2026-04-09T08:00:00Z",
    ingestedAt: "2026-04-08T09:02:00Z",
    company: "N",
    hasExceptions: false,
  },

  // ── Pending / Awaiting Payment (1) ───────────────────────────────
  {
    id: "SO5650000",
    channelOrderNo: "SHO-8810234-US",
    referenceNo: "REF-5650000",
    channel: "shopify",
    channelName: "Shopify US Store",
    status: "awaiting_payment",
    dropShipStatus: "none",
    isExpedited: false,
    isPaid: false,
    hasShipment: false,
    isDomestic: false,
    holdReason: null,
    customer: { name: "Carlos Mendez", country: "BR" },
    lineItems: [
      {
        id: "li-031",
        channelSku: "SHP-RB-19579-2PK",
        channelProductName: "RB-19579-2PK",
        qty: 1,
        unitPrice: 27.98,
        omsSku: "RB-19579-2PK",
        omsProductName: "RunBoost 19579 2-Pack",
        omsMatched: true,
        warehouseId: "wh-02",
        warehouseName: "LA-WH-02",
        warehouseSku: "WH-002700",
        availQty: 30,
        backorderQty: 0,
        location: "F-04-2",
        defaultVendor: "OTB Supplies",
        warehouseMapped: true,
        issues: [],
      },
    ],
    grandTotal: 27.98,
    totalQty: 1,
    warehouseName: "LA-WH-02",
    orderDate: "2026-04-21T08:00:00Z",
    shipDate: null,
    ingestedAt: "2026-04-21T08:02:00Z",
    company: "OTB",
    hasExceptions: false,
  },
]
