import type { SystemEvent } from './types'

export const mockEvents: SystemEvent[] = [
  {
    id: 'evt-001',
    eventType: 'order.created',
    category: 'order',
    entityType: 'order',
    entityId: 'SO-2024-10001',
    status: 'success',
    source: 'Shopify Webhook',
    triggeredBy: 'system',
    timestamp: '2026-04-20T09:12:34Z',
    durationMs: 243,
    tags: ['shopify', 'new-order'],
    requestPayload: {
      shop: 'acme-store.myshopify.com',
      event: 'orders/create',
      order_id: 5001234567,
      order_number: 'SO-2024-10001',
      total_price: '299.00',
      currency: 'USD',
      line_items: [
        { sku: 'SKU-A001', quantity: 2, price: '99.50' },
        { sku: 'SKU-B003', quantity: 1, price: '100.00' },
      ],
      shipping_address: {
        name: 'John Doe',
        city: 'New York',
        country: 'US',
        zip: '10001',
      },
    },
    responsePayload: {
      success: true,
      oms_order_id: 'SO-2024-10001',
      status: 'pending',
      message: 'Order created successfully',
    },
  },
  {
    id: 'evt-002',
    eventType: 'api.webhook.failed',
    category: 'api',
    entityType: 'webhook',
    entityId: 'WH-TK-88821',
    status: 'failed',
    source: 'TikTok Shop',
    triggeredBy: 'system',
    timestamp: '2026-04-20T09:05:11Z',
    durationMs: 5023,
    errorMessage: 'Request timeout after 5000ms. Upstream returned no response.',
    errorCode: 'UPSTREAM_TIMEOUT',
    tags: ['tiktok', 'webhook', 'timeout'],
    requestPayload: {
      platform: 'tiktok_shop',
      event_type: 'ORDER_STATUS_UPDATE',
      order_id: 'TK-20240420-00821',
      new_status: 'shipped',
      tracking_number: 'SF1234567890',
      carrier: 'SF Express',
    },
    responsePayload: {
      success: false,
      error: 'UPSTREAM_TIMEOUT',
      message: 'Request timeout after 5000ms',
      retried: true,
      retry_count: 3,
    },
  },
  {
    id: 'evt-003',
    eventType: 'order.fulfilment.confirmed',
    category: 'order',
    entityType: 'order',
    entityId: 'SO-2024-09988',
    status: 'success',
    source: 'Warehouse WMS',
    triggeredBy: 'wms-sync-job',
    timestamp: '2026-04-20T08:55:00Z',
    durationMs: 128,
    tags: ['fulfilment', 'wms'],
    requestPayload: {
      wms_order_id: 'WMS-9988-A',
      oms_order_id: 'SO-2024-09988',
      warehouse_code: 'WH-SH-001',
      packed_at: '2026-04-20T08:50:00Z',
      packages: [
        { tracking_no: 'YD0012345678', carrier: 'YTO', weight_kg: 1.2 },
      ],
    },
    responsePayload: {
      success: true,
      oms_order_id: 'SO-2024-09988',
      status: 'shipped',
      tracking_synced: true,
    },
  },
  {
    id: 'evt-004',
    eventType: 'automation.hold-rule.triggered',
    category: 'automation',
    entityType: 'order',
    entityId: 'SO-2024-10003',
    status: 'warning',
    source: 'Automation Engine',
    triggeredBy: 'rule:HIGH_VALUE_ORDER',
    timestamp: '2026-04-20T08:48:30Z',
    durationMs: 56,
    tags: ['hold', 'automation', 'high-value'],
    requestPayload: {
      rule_id: 'RULE-001',
      rule_name: 'High Value Order Review',
      order_id: 'SO-2024-10003',
      order_total: 1500.00,
      threshold: 1000.00,
      condition: 'total_price > threshold',
    },
    responsePayload: {
      action: 'hold',
      order_id: 'SO-2024-10003',
      hold_reason: 'Order value exceeds review threshold',
      notification_sent: true,
      assigned_to: 'ops-team@acme.com',
    },
  },
  {
    id: 'evt-005',
    eventType: 'inventory.sync.completed',
    category: 'inventory',
    entityType: 'sku',
    entityId: 'SKU-A001',
    status: 'success',
    source: 'ERP Sync',
    triggeredBy: 'scheduled-job',
    timestamp: '2026-04-20T08:30:00Z',
    durationMs: 892,
    tags: ['inventory', 'erp', 'sync'],
    requestPayload: {
      job_id: 'SYNC-20260420-083000',
      sku_list: ['SKU-A001', 'SKU-A002', 'SKU-B003'],
      warehouse: 'WH-SH-001',
      erp_system: 'SAP',
    },
    responsePayload: {
      synced_count: 3,
      updated: [
        { sku: 'SKU-A001', old_qty: 120, new_qty: 98, delta: -22 },
        { sku: 'SKU-A002', old_qty: 45, new_qty: 45, delta: 0 },
        { sku: 'SKU-B003', old_qty: 0, new_qty: 30, delta: 30 },
      ],
      failed: [],
    },
  },
  {
    id: 'evt-006',
    eventType: 'purchase.po.created',
    category: 'purchase',
    entityType: 'purchase_order',
    entityId: 'PO-2024-00456',
    status: 'success',
    source: 'OMS Internal',
    triggeredBy: 'user:jane.ops@acme.com',
    timestamp: '2026-04-20T08:20:15Z',
    durationMs: 315,
    tags: ['purchase', 'po'],
    requestPayload: {
      supplier_id: 'SUP-001',
      supplier_name: 'Guangzhou Supplier Co.',
      items: [
        { sku: 'SKU-A001', qty: 200, unit_price: 45.00 },
        { sku: 'SKU-C005', qty: 100, unit_price: 32.50 },
      ],
      expected_arrival: '2026-05-10',
      currency: 'CNY',
    },
    responsePayload: {
      po_id: 'PO-2024-00456',
      status: 'draft',
      total_amount: 12250.00,
      currency: 'CNY',
      created_at: '2026-04-20T08:20:15Z',
    },
  },
  {
    id: 'evt-007',
    eventType: 'api.stock.query.failed',
    category: 'api',
    entityType: 'integration',
    entityId: 'INT-ERP-SAP',
    status: 'failed',
    source: 'SAP ERP Integration',
    triggeredBy: 'system',
    timestamp: '2026-04-20T08:15:44Z',
    durationMs: 3001,
    errorMessage: 'SAP RFC connection refused. Check VPN or firewall settings.',
    errorCode: 'CONNECTION_REFUSED',
    tags: ['sap', 'erp', 'connection-error'],
    requestPayload: {
      integration: 'SAP_ERP',
      rfc_function: 'BAPI_MATERIAL_GET_ALL',
      parameters: {
        plant: '1000',
        material_list: ['SKU-A001', 'SKU-D007'],
      },
    },
    responsePayload: {
      success: false,
      error_code: 'CONNECTION_REFUSED',
      message: 'RFC connection to SAP host 10.0.1.15:3300 refused',
      attempted_at: '2026-04-20T08:15:44Z',
    },
  },
  {
    id: 'evt-008',
    eventType: 'order.cancelled',
    category: 'order',
    entityType: 'order',
    entityId: 'SO-2024-09901',
    status: 'success',
    source: 'Merchant Portal',
    triggeredBy: 'user:merchant-admin',
    timestamp: '2026-04-20T07:58:00Z',
    durationMs: 198,
    tags: ['cancel', 'order', 'merchant-initiated'],
    requestPayload: {
      order_id: 'SO-2024-09901',
      cancel_reason: 'customer_request',
      cancel_note: 'Customer changed mind before shipment',
      refund_amount: 199.00,
      refund_method: 'original_payment',
    },
    responsePayload: {
      success: true,
      order_id: 'SO-2024-09901',
      status: 'cancelled',
      refund_initiated: true,
      refund_reference: 'REF-2024-09901-A',
    },
  },
  {
    id: 'evt-009',
    eventType: 'system.config.updated',
    category: 'system',
    entityType: 'config',
    entityId: 'CFG-WAREHOUSE-ROUTING',
    status: 'success',
    source: 'Admin Console',
    triggeredBy: 'user:admin@acme.com',
    timestamp: '2026-04-20T07:30:00Z',
    durationMs: 87,
    tags: ['config', 'warehouse', 'routing'],
    requestPayload: {
      config_key: 'warehouse.routing.priority',
      old_value: { WH_SH_001: 1, WH_BJ_001: 2 },
      new_value: { WH_SH_001: 2, WH_BJ_001: 1 },
      change_reason: 'Beijing warehouse capacity increase',
    },
    responsePayload: {
      success: true,
      config_key: 'warehouse.routing.priority',
      applied_at: '2026-04-20T07:30:00Z',
      effective_immediately: true,
    },
  },
  {
    id: 'evt-010',
    eventType: 'automation.mapping.sync',
    category: 'automation',
    entityType: 'product_mapping',
    entityId: 'MAP-SHOPIFY-SKU',
    status: 'warning',
    source: 'Automation Engine',
    triggeredBy: 'scheduled-job',
    timestamp: '2026-04-20T07:00:00Z',
    durationMs: 2140,
    tags: ['mapping', 'sku', 'shopify'],
    requestPayload: {
      job: 'product_mapping_sync',
      platform: 'shopify',
      shop: 'acme-store.myshopify.com',
      total_variants: 450,
    },
    responsePayload: {
      synced: 442,
      skipped: 5,
      conflicts: 3,
      conflict_details: [
        { platform_sku: 'SHP-X001', matched_skus: ['SKU-A001', 'SKU-A001-V2'], reason: 'duplicate_barcode' },
      ],
    },
  },
  {
    id: 'evt-011',
    eventType: 'order.payment.verified',
    category: 'order',
    entityType: 'order',
    entityId: 'SO-2024-10007',
    status: 'success',
    source: 'Payment Gateway',
    triggeredBy: 'system',
    timestamp: '2026-04-20T06:45:22Z',
    durationMs: 412,
    tags: ['payment', 'stripe'],
    requestPayload: {
      gateway: 'stripe',
      charge_id: 'ch_3NxKLMAbcDef12345',
      amount: 850.00,
      currency: 'USD',
      order_id: 'SO-2024-10007',
    },
    responsePayload: {
      verified: true,
      charge_status: 'succeeded',
      payment_method: 'visa_****4242',
      order_status_updated: 'paid',
    },
  },
  {
    id: 'evt-012',
    eventType: 'inventory.alert.low-stock',
    category: 'inventory',
    entityType: 'sku',
    entityId: 'SKU-B003',
    status: 'warning',
    source: 'Inventory Monitor',
    triggeredBy: 'system',
    timestamp: '2026-04-20T06:00:00Z',
    durationMs: 34,
    tags: ['low-stock', 'alert'],
    requestPayload: {
      sku: 'SKU-B003',
      warehouse: 'WH-SH-001',
      current_qty: 8,
      safety_stock: 20,
      reorder_point: 15,
    },
    responsePayload: {
      alert_sent: true,
      notification_channels: ['email', 'dashboard'],
      recipients: ['procurement@acme.com'],
      suggested_po_qty: 100,
    },
  },
  {
    id: 'evt-013',
    eventType: 'api.tracking.push.failed',
    category: 'api',
    entityType: 'order',
    entityId: 'SO-2024-09950',
    status: 'failed',
    source: 'Amazon SP-API',
    triggeredBy: 'system',
    timestamp: '2026-04-19T23:30:10Z',
    durationMs: 1892,
    errorMessage: 'Amazon API returned 400: InvalidTrackingNumber. The tracking number format is not recognized.',
    errorCode: 'INVALID_TRACKING_NUMBER',
    tags: ['amazon', 'tracking', 'push-failed'],
    requestPayload: {
      platform: 'amazon',
      marketplace: 'US',
      amazon_order_id: '114-1234567-8901234',
      carrier: 'UPS',
      tracking_number: 'INVALID-TRACK-001',
      ship_date: '2026-04-19',
    },
    responsePayload: {
      success: false,
      http_status: 400,
      amazon_error_code: 'InvalidTrackingNumber',
      amazon_message: 'The tracking number INVALID-TRACK-001 is not a valid UPS tracking number format.',
    },
  },
  {
    id: 'evt-014',
    eventType: 'system.health.check',
    category: 'system',
    entityType: 'service',
    entityId: 'SVC-ALL',
    status: 'success',
    source: 'Health Monitor',
    triggeredBy: 'scheduled-job',
    timestamp: '2026-04-19T23:00:00Z',
    durationMs: 3240,
    tags: ['health', 'monitoring'],
    requestPayload: {
      check_type: 'full',
      services: ['oms-core', 'wms-connector', 'erp-bridge', 'notification-service'],
    },
    responsePayload: {
      overall: 'healthy',
      results: [
        { service: 'oms-core', status: 'healthy', latency_ms: 45 },
        { service: 'wms-connector', status: 'healthy', latency_ms: 120 },
        { service: 'erp-bridge', status: 'healthy', latency_ms: 89 },
        { service: 'notification-service', status: 'healthy', latency_ms: 32 },
      ],
    },
  },
  {
    id: 'evt-015',
    eventType: 'purchase.po.supplier-confirmed',
    category: 'purchase',
    entityType: 'purchase_order',
    entityId: 'PO-2024-00443',
    status: 'pending',
    source: 'Supplier Portal',
    triggeredBy: 'user:supplier-001',
    timestamp: '2026-04-19T22:15:00Z',
    durationMs: 267,
    tags: ['po', 'supplier-confirm', 'pending-review'],
    requestPayload: {
      po_id: 'PO-2024-00443',
      supplier_id: 'SUP-001',
      confirmed_items: [
        { sku: 'SKU-A001', confirmed_qty: 200, delivery_date: '2026-05-12' },
        { sku: 'SKU-C005', confirmed_qty: 80, delivery_date: '2026-05-15', note: 'Partial delivery, 20 units backordered' },
      ],
    },
    responsePayload: {
      po_id: 'PO-2024-00443',
      status: 'pending_ops_review',
      discrepancy_detected: true,
      discrepancy_detail: 'Supplier confirmed 80 of 100 units for SKU-C005',
      action_required: 'ops_team',
    },
  },
]
