import type {
  Warehouse,
  SkuInventory,
  LedgerEntry,
  SafetyStockConfig,
  SyncChannel,
  AnalyticsSku,
} from "./types"

export const mockWarehouses: Warehouse[] = [
  {
    id: "wh-001",
    name: "Los Angeles DC",
    code: "LA-DC",
    type: "physical",
    region: "US - West",
    address: "1234 Industrial Blvd, Los Angeles, CA 90001",
    status: "active",
    skuCount: 248,
    totalUnits: 15420,
    connectedChannel: "Shopify US",
  },
  {
    id: "wh-002",
    name: "New York DC",
    code: "NY-DC",
    type: "physical",
    region: "US - East",
    address: "567 Commerce Ave, Brooklyn, NY 11201",
    status: "active",
    skuCount: 193,
    totalUnits: 9870,
    connectedChannel: "Shopify US",
  },
  {
    id: "wh-003",
    name: "Amazon FBA - US",
    code: "FBA-US",
    type: "fba",
    region: "US (Multi-node)",
    status: "active",
    skuCount: 156,
    totalUnits: 6340,
    connectedChannel: "Amazon US",
  },
  {
    id: "wh-004",
    name: "Shanghai 3PL",
    code: "SHA-3PL",
    type: "3pl",
    region: "CN - Shanghai",
    address: "88 Logistics Road, Minhang District, Shanghai",
    status: "active",
    skuCount: 312,
    totalUnits: 28900,
    connectedChannel: "Amazon JP",
  },
  {
    id: "wh-005",
    name: "Amazon FBA - JP",
    code: "FBA-JP",
    type: "fba",
    region: "JP (Multi-node)",
    status: "disconnected",
    skuCount: 89,
    totalUnits: 2100,
    connectedChannel: "Amazon JP",
  },
]

/**
 * SKU 库存数据
 * ATP = wmsAvailable − wmsOpenOrder(仅 availableIsNet=false 仓库) − omsLockTotal
 * damage 仅展示，不参与 ATP 计算
 */
export const mockSkuInventory: SkuInventory[] = [
  {
    skuId: "sku-001",
    skuCode: "SHOE-NK-001-BLK-42",
    productName: "Nike Air Max 270 Black Size 42",
    category: "Footwear",
    // WMS 各仓可用合计: 110+75+85+40 = 310
    wmsAvailable: 310,
    wmsOpenOrder: 28,      // WMS open order 缓存
    omsLocks: { openOrder: 0, locked: 5, allocated: 12, pendingWmsSync: 0 },
    omsLockTotal: 17,
    damage: 3,
    atpUnits: 265,           // 310 - 28 - 17 = 265
    onHand: 340,
    wmsAllocate: 8,
    inbound: 200,
    warehouseBreakdown: [
      { warehouseId: "wh-001", warehouseName: "Los Angeles DC", warehouseType: "physical", warehouseCode: "LA-DC", onHand: 120, available: 110, wmsOpenOrder: 12, wmsAllocate: 3, damage: 2, inbound: 100, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-002", warehouseName: "New York DC", warehouseType: "physical", warehouseCode: "NY-DC", onHand: 80, available: 75, wmsOpenOrder: 8, wmsAllocate: 2, damage: 1, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-003", warehouseName: "Amazon FBA - US", warehouseType: "fba", warehouseCode: "FBA-US", onHand: 90, available: 85, wmsOpenOrder: 8, wmsAllocate: 3, damage: 0, inbound: 100, availableIsNet: false, lastSyncAt: "2026-04-20T08:45:00Z", syncStatus: "synced" },
      { warehouseId: "wh-004", warehouseName: "Shanghai 3PL", warehouseType: "3pl", warehouseCode: "SHA-3PL", onHand: 50, available: 40, wmsOpenOrder: 0, wmsAllocate: 0, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T07:00:00Z", syncStatus: "delayed" },
    ],
    safetyStock: 50,
    reorderPoint: 80,
    maxStock: 500,
    status: "normal",
    avgDailySales: 12,
    stockDays: 21,
    lastUpdated: "2026-04-20T09:00:00Z",
  },
  {
    skuId: "sku-002",
    skuCode: "SHOE-NK-001-WHT-40",
    productName: "Nike Air Max 270 White Size 40",
    category: "Footwear",
    wmsAvailable: 22,
    wmsOpenOrder: 5,
    omsLocks: { openOrder: 0, locked: 2, allocated: 3, pendingWmsSync: 0 },
    omsLockTotal: 5,
    damage: 1,
    atpUnits: 12,            // 22 - 5 - 5 = 12
    onHand: 28,
    wmsAllocate: 3,
    inbound: 0,
    warehouseBreakdown: [
      { warehouseId: "wh-001", warehouseName: "Los Angeles DC", warehouseType: "physical", warehouseCode: "LA-DC", onHand: 10, available: 9, wmsOpenOrder: 3, wmsAllocate: 1, damage: 1, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-002", warehouseName: "New York DC", warehouseType: "physical", warehouseCode: "NY-DC", onHand: 8, available: 7, wmsOpenOrder: 2, wmsAllocate: 1, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-003", warehouseName: "Amazon FBA - US", warehouseType: "fba", warehouseCode: "FBA-US", onHand: 10, available: 6, wmsOpenOrder: 0, wmsAllocate: 1, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T08:45:00Z", syncStatus: "synced" },
    ],
    safetyStock: 50,
    reorderPoint: 80,
    maxStock: 500,
    status: "low",
    avgDailySales: 8,
    stockDays: 1,
    lastUpdated: "2026-04-20T07:15:00Z",
  },
  {
    skuId: "sku-003",
    skuCode: "BAG-GU-002-BRN",
    productName: "Gucci Soho Disco Bag Brown",
    category: "Bags",
    wmsAvailable: 0,
    wmsOpenOrder: 0,
    omsLocks: { openOrder: 0, locked: 0, allocated: 0, pendingWmsSync: 0 },
    omsLockTotal: 0,
    damage: 0,
    atpUnits: 0,
    onHand: 0,
    wmsAllocate: 0,
    inbound: 50,
    warehouseBreakdown: [
      { warehouseId: "wh-001", warehouseName: "Los Angeles DC", warehouseType: "physical", warehouseCode: "LA-DC", onHand: 0, available: 0, wmsOpenOrder: 0, wmsAllocate: 0, damage: 0, inbound: 50, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
    ],
    safetyStock: 20,
    reorderPoint: 30,
    maxStock: 200,
    status: "out",
    avgDailySales: 3,
    stockDays: 0,
    lastUpdated: "2026-04-19T18:00:00Z",
  },
  {
    skuId: "sku-004",
    skuCode: "TEE-SS-003-RED-M",
    productName: "Classic Cotton T-Shirt Red M",
    category: "Apparel",
    wmsAvailable: 1180,
    wmsOpenOrder: 45,
    omsLocks: { openOrder: 0, locked: 8, allocated: 20, pendingWmsSync: 0 },
    omsLockTotal: 28,
    damage: 7,
    atpUnits: 1107,          // 1180 - 45 - 28 = 1107
    onHand: 1240,
    wmsAllocate: 15,
    inbound: 0,
    warehouseBreakdown: [
      { warehouseId: "wh-001", warehouseName: "Los Angeles DC", warehouseType: "physical", warehouseCode: "LA-DC", onHand: 400, available: 385, wmsOpenOrder: 20, wmsAllocate: 5, damage: 5, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-002", warehouseName: "New York DC", warehouseType: "physical", warehouseCode: "NY-DC", onHand: 340, available: 335, wmsOpenOrder: 15, wmsAllocate: 5, damage: 2, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-003", warehouseName: "Amazon FBA - US", warehouseType: "fba", warehouseCode: "FBA-US", onHand: 300, available: 290, wmsOpenOrder: 10, wmsAllocate: 3, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T08:45:00Z", syncStatus: "synced" },
      { warehouseId: "wh-004", warehouseName: "Shanghai 3PL", warehouseType: "3pl", warehouseCode: "SHA-3PL", onHand: 200, available: 170, wmsOpenOrder: 0, wmsAllocate: 2, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T07:00:00Z", syncStatus: "delayed" },
    ],
    safetyStock: 100,
    reorderPoint: 150,
    maxStock: 800,
    status: "overstock",
    avgDailySales: 5,
    stockDays: 220,
    lastUpdated: "2026-04-20T09:00:00Z",
  },
  {
    skuId: "sku-005",
    skuCode: "WATCH-CK-004-BLK",
    productName: "Calvin Klein Classic Watch Black",
    category: "Accessories",
    wmsAvailable: 58,
    wmsOpenOrder: 6,
    omsLocks: { openOrder: 0, locked: 1, allocated: 4, pendingWmsSync: 0 },
    omsLockTotal: 5,
    damage: 2,
    atpUnits: 47,            // 58 - 6 - 5 = 47
    onHand: 65,
    wmsAllocate: 4,
    inbound: 0,
    warehouseBreakdown: [
      { warehouseId: "wh-001", warehouseName: "Los Angeles DC", warehouseType: "physical", warehouseCode: "LA-DC", onHand: 30, available: 28, wmsOpenOrder: 4, wmsAllocate: 2, damage: 2, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-002", warehouseName: "New York DC", warehouseType: "physical", warehouseCode: "NY-DC", onHand: 20, available: 18, wmsOpenOrder: 2, wmsAllocate: 1, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-003", warehouseName: "Amazon FBA - US", warehouseType: "fba", warehouseCode: "FBA-US", onHand: 15, available: 12, wmsOpenOrder: 0, wmsAllocate: 1, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T08:45:00Z", syncStatus: "synced" },
    ],
    safetyStock: 30,
    reorderPoint: 40,
    maxStock: 200,
    status: "normal",
    avgDailySales: 2,
    stockDays: 22,
    lastUpdated: "2026-04-20T06:45:00Z",
  },
  {
    skuId: "sku-006",
    skuCode: "SHOE-AD-005-BLU-44",
    productName: "Adidas Ultraboost Blue Size 44",
    category: "Footwear",
    wmsAvailable: 15,
    wmsOpenOrder: 4,
    omsLocks: { openOrder: 1, locked: 3, allocated: 2, pendingWmsSync: 0 },
    omsLockTotal: 6,
    damage: 0,
    atpUnits: 5,             // 15 - 4 - 6 = 5
    onHand: 18,
    wmsAllocate: 2,
    inbound: 100,
    warehouseBreakdown: [
      { warehouseId: "wh-001", warehouseName: "Los Angeles DC", warehouseType: "physical", warehouseCode: "LA-DC", onHand: 8, available: 7, wmsOpenOrder: 2, wmsAllocate: 1, damage: 0, inbound: 50, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-002", warehouseName: "New York DC", warehouseType: "physical", warehouseCode: "NY-DC", onHand: 4, available: 3, wmsOpenOrder: 2, wmsAllocate: 1, damage: 0, inbound: 50, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-003", warehouseName: "Amazon FBA - US", warehouseType: "fba", warehouseCode: "FBA-US", onHand: 6, available: 5, wmsOpenOrder: 0, wmsAllocate: 0, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T08:45:00Z", syncStatus: "synced" },
    ],
    safetyStock: 40,
    reorderPoint: 60,
    maxStock: 400,
    status: "low",
    avgDailySales: 7,
    stockDays: 0,
    lastUpdated: "2026-04-20T08:00:00Z",
  },
  {
    skuId: "sku-007",
    skuCode: "ELEC-AP-006-PRO",
    productName: "AirPods Pro (2nd Gen)",
    category: "Electronics",
    wmsAvailable: 195,
    wmsOpenOrder: 22,
    omsLocks: { openOrder: 0, locked: 4, allocated: 9, pendingWmsSync: 0 },
    omsLockTotal: 13,
    damage: 0,
    atpUnits: 160,           // 195 - 22 - 13 = 160
    onHand: 230,
    wmsAllocate: 10,
    inbound: 50,
    warehouseBreakdown: [
      { warehouseId: "wh-001", warehouseName: "Los Angeles DC", warehouseType: "physical", warehouseCode: "LA-DC", onHand: 80, available: 72, wmsOpenOrder: 10, wmsAllocate: 4, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-002", warehouseName: "New York DC", warehouseType: "physical", warehouseCode: "NY-DC", onHand: 70, available: 63, wmsOpenOrder: 8, wmsAllocate: 3, damage: 0, inbound: 50, availableIsNet: false, lastSyncAt: "2026-04-20T09:00:00Z", syncStatus: "synced" },
      { warehouseId: "wh-003", warehouseName: "Amazon FBA - US", warehouseType: "fba", warehouseCode: "FBA-US", onHand: 80, available: 60, wmsOpenOrder: 4, wmsAllocate: 3, damage: 0, inbound: 0, availableIsNet: false, lastSyncAt: "2026-04-20T08:45:00Z", syncStatus: "synced" },
    ],
    safetyStock: 60,
    reorderPoint: 80,
    maxStock: 500,
    status: "normal",
    avgDailySales: 15,
    stockDays: 10,
    lastUpdated: "2026-04-20T09:30:00Z",
  },
  {
    skuId: "sku-008",
    skuCode: "SKINCARE-SK-007-SPF",
    productName: "SK-II Facial Treatment SPF50",
    category: "Beauty",
    wmsAvailable: 0,
    wmsOpenOrder: 0,
    omsLocks: { openOrder: 0, locked: 0, allocated: 0, pendingWmsSync: 0 },
    omsLockTotal: 0,
    damage: 0,
    atpUnits: 0,
    onHand: 0,
    wmsAllocate: 0,
    inbound: 0,
    warehouseBreakdown: [],
    safetyStock: 30,
    reorderPoint: 50,
    maxStock: 300,
    status: "out",
    avgDailySales: 4,
    stockDays: 0,
    lastUpdated: "2026-04-18T12:00:00Z",
  },
]

export const mockLedger: LedgerEntry[] = [
  {
    id: "led-001",
    timestamp: "2026-04-20T09:30:00Z",
    skuId: "sku-001",
    skuCode: "SHOE-NK-001-BLK-42",
    productName: "Nike Air Max 270 Black Size 42",
    warehouseId: "wh-001",
    warehouseName: "Los Angeles DC",
    type: "inbound",
    quantity: 200,
    beforeStock: 65,
    afterStock: 265,
    referenceNo: "PO-2026-0412",
    reason: "PO-2026-0412 goods received at LA-DC",
  },
  {
    id: "led-002",
    timestamp: "2026-04-20T08:15:00Z",
    skuId: "sku-001",
    skuCode: "SHOE-NK-001-BLK-42",
    productName: "Nike Air Max 270 Black Size 42",
    warehouseId: undefined,
    warehouseName: undefined,
    type: "oms_lock",
    quantity: -5,
    beforeStock: 270,
    afterStock: 265,
    referenceNo: "SO-2026-8821",
    reason: "Order SO-2026-8821 routing — warehouse search lock applied",
  },
  {
    id: "led-003",
    timestamp: "2026-04-20T08:00:00Z",
    skuId: "sku-007",
    skuCode: "ELEC-AP-006-PRO",
    productName: "AirPods Pro (2nd Gen)",
    warehouseId: "wh-003",
    warehouseName: "Amazon FBA - US",
    type: "outbound",
    quantity: -15,
    beforeStock: 175,
    afterStock: 160,
    referenceNo: "SO-2026-8820",
    reason: "WMS consumed SO-2026-8820 — open order cleared, stock deducted",
  },
  {
    id: "led-004",
    timestamp: "2026-04-20T07:00:00Z",
    skuId: "sku-002",
    skuCode: "SHOE-NK-001-WHT-40",
    productName: "Nike Air Max 270 White Size 40",
    warehouseId: "wh-002",
    warehouseName: "New York DC",
    type: "outbound",
    quantity: -5,
    beforeStock: 17,
    afterStock: 12,
    referenceNo: "SO-2026-8819",
    reason: "WMS consumed SO-2026-8819 — open order cleared, stock deducted",
  },
  {
    id: "led-005",
    timestamp: "2026-04-19T16:45:00Z",
    skuId: "sku-001",
    skuCode: "SHOE-NK-001-BLK-42",
    productName: "Nike Air Max 270 Black Size 42",
    warehouseId: undefined,
    warehouseName: undefined,
    type: "oms_lock",
    quantity: -12,
    beforeStock: 282,
    afterStock: 270,
    referenceNo: "SO-2026-8818",
    reason: "Order SO-2026-8818 allocated to LA-DC — allocated lock applied, Kafka message sent",
  },
  {
    id: "led-006",
    timestamp: "2026-04-19T16:30:00Z",
    skuId: "sku-004",
    skuCode: "TEE-SS-003-RED-M",
    productName: "Classic Cotton T-Shirt Red M",
    warehouseId: "wh-001",
    warehouseName: "Los Angeles DC",
    type: "return",
    quantity: 3,
    beforeStock: 1104,
    afterStock: 1107,
    referenceNo: "RTN-2026-0098",
    reason: "Customer return RMA RTN-2026-0098 restocked at LA-DC",
  },
  {
    id: "led-007",
    timestamp: "2026-04-19T14:00:00Z",
    skuId: "sku-005",
    skuCode: "WATCH-CK-004-BLK",
    productName: "Calvin Klein Classic Watch Black",
    warehouseId: "wh-001",
    warehouseName: "Los Angeles DC",
    type: "transfer",
    quantity: -10,
    beforeStock: 55,
    afterStock: 45,
    referenceNo: "TRF-2026-0044",
    reason: "Transfer TRF-2026-0044 — 10 units shipped from LA-DC to NY-DC",
  },
  {
    id: "led-008",
    timestamp: "2026-04-19T10:00:00Z",
    skuId: "sku-003",
    skuCode: "BAG-GU-002-BRN",
    productName: "Gucci Soho Disco Bag Brown",
    warehouseId: "wh-001",
    warehouseName: "Los Angeles DC",
    type: "adjustment",
    quantity: -3,
    beforeStock: 3,
    afterStock: 0,
    referenceNo: "ADJ-2026-0015",
    reason: "System adjustment ADJ-2026-0015 — damaged goods written off",
  },
  {
    id: "led-009",
    timestamp: "2026-04-19T09:30:00Z",
    skuId: "sku-001",
    skuCode: "SHOE-NK-001-BLK-42",
    productName: "Nike Air Max 270 Black Size 42",
    warehouseId: undefined,
    warehouseName: undefined,
    type: "oms_unlock",
    quantity: 8,
    beforeStock: 271,
    afterStock: 279,
    referenceNo: "SO-2026-8815",
    reason: "Order SO-2026-8815 cancelled — routing lock released, ATP restored",
  },
  {
    id: "led-010",
    timestamp: "2026-04-18T11:00:00Z",
    skuId: "sku-001",
    skuCode: "SHOE-NK-001-BLK-42",
    productName: "Nike Air Max 270 Black Size 42",
    warehouseId: "wh-004",
    warehouseName: "Shanghai 3PL",
    type: "inbound",
    quantity: 500,
    beforeStock: 0,
    afterStock: 500,
    referenceNo: "PO-2026-0389",
    reason: "PO-2026-0389 goods received at SHA-3PL (WMS sync confirmed)",
  },
]

export const mockSafetyStock: SafetyStockConfig[] = mockSkuInventory.map((sku) => ({
  skuId: sku.skuId,
  skuCode: sku.skuCode,
  productName: sku.productName,
  currentStock: sku.atpUnits,
  safetyStock: sku.safetyStock,
  reorderPoint: sku.reorderPoint,
  maxStock: sku.maxStock,
  leadTimeDays: Math.floor(Math.random() * 10) + 5,
}))

export const mockSyncChannels: SyncChannel[] = [
  {
    id: "ch-001",
    name: "Shopify US Store",
    type: "shopify",
    platform: "Shopify",
    enabled: true,
    syncMode: "15min",
    bufferStock: 5,
    syncRatio: 100,
    warehouses: ["wh-001", "wh-002"],
    skuFilter: "all",
    skuFilterList: [],
    lastSyncAt: "2026-04-20T09:45:00Z",
    lastSyncStatus: "success",
    pendingUpdates: 0,
  },
  {
    id: "ch-002",
    name: "Amazon US",
    type: "amazon",
    platform: "Amazon",
    enabled: true,
    syncMode: "realtime",
    bufferStock: 10,
    syncRatio: 90,
    warehouses: ["wh-003"],
    skuFilter: "blacklist",
    skuFilterList: ["sku-004"],
    lastSyncAt: "2026-04-20T09:58:00Z",
    lastSyncStatus: "success",
    pendingUpdates: 3,
  },
  {
    id: "ch-003",
    name: "Amazon JP",
    type: "amazon",
    platform: "Amazon",
    enabled: true,
    syncMode: "hourly",
    bufferStock: 20,
    syncRatio: 80,
    warehouses: ["wh-004", "wh-005"],
    skuFilter: "whitelist",
    skuFilterList: ["sku-001", "sku-005", "sku-007"],
    lastSyncAt: "2026-04-20T09:00:00Z",
    lastSyncStatus: "partial",
    pendingUpdates: 12,
  },
  {
    id: "ch-004",
    name: "Shopify EU Store",
    type: "shopify",
    platform: "Shopify",
    enabled: false,
    syncMode: "manual",
    bufferStock: 0,
    syncRatio: 100,
    warehouses: [],
    skuFilter: "all",
    skuFilterList: [],
    lastSyncAt: "2026-04-15T10:00:00Z",
    lastSyncStatus: "pending",
    pendingUpdates: 0,
  },
]

export const mockAnalytics: AnalyticsSku[] = [
  { skuId: "sku-007", skuCode: "ELEC-AP-006-PRO", productName: "AirPods Pro (2nd Gen)", category: "Electronics", currentStock: 160, stockValue: 40000, avgDailySales: 15, stockDays: 10, stockAge: 8, totalSold30d: 450, turnoverRate: 24 },
  { skuId: "sku-001", skuCode: "SHOE-NK-001-BLK-42", productName: "Nike Air Max 270 Black Size 42", category: "Footwear", currentStock: 262, stockValue: 36680, avgDailySales: 12, stockDays: 21, stockAge: 15, totalSold30d: 360, turnoverRate: 15 },
  { skuId: "sku-002", skuCode: "SHOE-NK-001-WHT-40", productName: "Nike Air Max 270 White Size 40", category: "Footwear", currentStock: 11, stockValue: 1540, avgDailySales: 8, stockDays: 1, stockAge: 20, totalSold30d: 240, turnoverRate: 26 },
  { skuId: "sku-006", skuCode: "SHOE-AD-005-BLU-44", productName: "Adidas Ultraboost Blue Size 44", category: "Footwear", currentStock: 5, stockValue: 850, avgDailySales: 7, stockDays: 0, stockAge: 12, totalSold30d: 210, turnoverRate: 35 },
  { skuId: "sku-005", skuCode: "WATCH-CK-004-BLK", productName: "Calvin Klein Classic Watch Black", category: "Accessories", currentStock: 45, stockValue: 6750, avgDailySales: 2, stockDays: 22, stockAge: 45, totalSold30d: 60, turnoverRate: 4 },
  { skuId: "sku-004", skuCode: "TEE-SS-003-RED-M", productName: "Classic Cotton T-Shirt Red M", category: "Apparel", currentStock: 1100, stockValue: 16500, avgDailySales: 5, stockDays: 220, stockAge: 90, totalSold30d: 150, turnoverRate: 1.8 },
  { skuId: "sku-003", skuCode: "BAG-GU-002-BRN", productName: "Gucci Soho Disco Bag Brown", category: "Bags", currentStock: 0, stockValue: 0, avgDailySales: 3, stockDays: 0, stockAge: 0, totalSold30d: 90, turnoverRate: 0 },
  { skuId: "sku-008", skuCode: "SKINCARE-SK-007-SPF", productName: "SK-II Facial Treatment SPF50", category: "Beauty", currentStock: 0, stockValue: 0, avgDailySales: 4, stockDays: 0, stockAge: 0, totalSold30d: 120, turnoverRate: 0 },
]

export const inventoryStats = {
  totalSkus: mockSkuInventory.length,
  activeWarehouses: mockWarehouses.filter((w) => w.status === "active").length,
  totalWarehouses: mockWarehouses.length,
  totalStockValue: 102320,
  lowStockCount: mockSkuInventory.filter((s) => s.status === "low").length,
  outOfStockCount: mockSkuInventory.filter((s) => s.status === "out").length,
  pendingSyncCount: mockSyncChannels.reduce((acc, c) => acc + c.pendingUpdates, 0),
  totalOmsLocks: mockSkuInventory.reduce((acc, s) => acc + s.omsLockTotal, 0),
}
